apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foodieshare-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
spec:
  tls:
  - hosts:
    - foodieshare.com
    - api.foodieshare.com
    secretName: foodieshare-tls
  rules:
  - host: foodieshare.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
  - host: api.foodieshare.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 3000

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: foodieshare-cert
spec:
  secretName: foodieshare-tls
  dnsNames:
  - foodieshare.com
  - api.foodieshare.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer