name: Intégration Continue

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Installer les dépendances
        run: npm install
      - name: Lancer les tests unitaires
        run: npm test
      - name: Lancer les tests E2E
        run: npx playwright test